# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simple-web-ui-service
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: 80
  selector:
    app: simple-web-ui
